on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: check labels name
        if: contains( toJson(github), '/posts/666/' )
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for your comments! Welcome to join, and `Collaborator` permissions will be granted to you soon :clap::clap::clap:'
            })
